SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += /app/submission/axi_lite_wr_slave.v
TOPLEVEL = axi_lite_wr_slave
MODULE = test_axi_lite_wr_slave

include $(shell cocotb-config --makefiles)/Makefile.sim
