SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += /app/submission/forwarding_unit.v
TOPLEVEL = forwarding_unit
MODULE = test_forwarding_unit

include $(shell cocotb-config --makefiles)/Makefile.sim
